;Augusto Vaz Rodrigues
;Gustavo Dias Martins
;Pedro Henrique Ribeiro Dantas
;Yves Yuji Carvalho

(load ".../Zubber/motorista.lisp")
(load ".../Zubber/usuario.lisp")
(load ".../Zubber/warrior.lisp")

(Ler_motoristas)
(Ler_local)
(Ler_comercio ".../Zubber/arquivos/Itens_restaurantes.txt" 5)
(Ler_comercio ".../Zubber/arquivos/Itens_farmacias.txt" 4)
(Ler_comercio ".../Zubber/arquivos/Itens_supermercados.txt" 3)
(Ler_comercio ".../Zubber/arquivos/Itens_livrarias.txt" 2)

(defun Pedir_viagem()
	(Ler_dados_viagem)
	(setq Dest_aux Destino_servico)
	(setq Partida Loc_usuario)
	(setq Op_aux Tipo_servico)
	(setq Indice (Verif_livre Op_aux Partida ""))
	(setq Motorista_aux (nth Indice List_motorista))
	(setq Nome_aux (Motorista-Nome Motorista_aux))
	(setq Loc_atual (Motorista-Localizacao Motorista_aux))	
	(setq Aux_dest_final (make-Destino_final	:ID (Motorista-ID Motorista_aux)
																	:Loc_destino Dest_aux)
	)
	(setq List_dest_final (cons Aux_dest_final List_dest_final))
	
	(princ "Dados da viagem:")
	(terpri)
	(terpri)
	(format t "Seu/Sua motorista:  ~A" Nome_aux)
	(terpri)
	
	(setq Pos_Inicial (Verif_pos Partida))
	(setq Pos_Final (Verif_pos Dest_aux))
	(setq Pos_motorista (Verif_pos Loc_atual))
	(setq Cal1 (nth Pos_Inicial List_local))
	(setq Cal2 (nth Pos_Final List_local))
	(setq Cal3 (nth Pos_motorista List_local))
	(setq Lat_inicial (Local_rua-Latitude Cal1))
	(setq Long_inicial (Local_rua-Longitude Cal1))
	(setq Lat_final (Local_rua-Latitude Cal2))
	(setq Long_final (Local_rua-Longitude Cal2))
	(setq Lat_motorista (Local_rua-Latitude Cal3))
	(setq Long_motorista (Local_rua-Longitude Cal3))
	(setq Distancia_dest (Cal_distancia Lat_inicial Long_inicial Lat_final Long_final))
	(setq Distancia_chegada (Cal_distancia Lat_inicial Long_inicial Lat_motorista Long_motorista))
	(setq Valor_base 3)
	(setq Valor_km (* 1.33 Distancia_dest))
	(setq Valor_total (+ Valor_base Valor_km))

	(format t "Distancia ate voce ~A" Distancia_chegada)
	(terpri)
	(setq Tempo_chegada (/ Distancia_chegada 30))
	(format t "Chegara ate voce em (min):  ~A" (* Tempo_chegada 56.528))
	(terpri)
	(format t "Seu destino: ~A" Dest_aux)
	(terpri)
	(format t "Distancia ate seu destino (Km): ~A" Distancia_dest)
	(terpri)
	(setq Tempo_viagem (/ Distancia_dest 30))
	(format t "Chegara ao destino em (min):  ~A" (* Tempo_viagem 56.528))
	(terpri)
	(format t "Valor da viagem (R$):  ~A" Valor_total)
)

(defun Pedir_compra()
	(Ler_dados_compras)
	(setq Loc_compra_aux Loc_compras)
	(setq Loc_entrega_aux Destino_compra)
	(setq Op_aux Tipo_servico)
	(setq Indice (Verif_livre Op_aux Loc_entrega_aux Loc_compra_aux))
	(setq Motorista_aux (nth Indice List_motorista))
	(setq Nome_aux (Motorista-Nome Motorista_aux))
	(setq Loc_atual (Motorista-Localizacao Motorista_aux))
	(setq Aux_dest_final (make-Destino_final	:ID (Motorista-ID Motorista_aux)
																	:Loc_destino Loc_entrega_aux)
	)
	(setq List_dest_final (cons Aux_dest_final List_dest_final))
	
	(terpri)
	(princ "Dados da viagem:")
	(terpri)
	(terpri)
	(format t "Seu/Sua entregador(a):  ~A" Nome_aux)
	(terpri)
	
	(setq Pos_entrega (Verif_pos Loc_entrega_aux))
	(setq Pos_motorista (Verif_pos Loc_atual))
	(setq Cal1 (nth Pos_compra List_local))
	(setq Cal2 (nth Pos_entrega List_local))
	(setq Cal3 (nth Pos_motorista List_local))
	(setq Lat_compra (Local_rua-Latitude Cal1))
	(setq Long_compra (Local_rua-Longitude Cal1))
	(setq Lat_entrega (Local_rua-Latitude Cal2))
	(setq Long_entrega (Local_rua-Longitude Cal2))
	(setq Lat_motorista (Local_rua-Latitude Cal3))
	(setq Long_motorista (Local_rua-Longitude Cal3))
	(setq Distancia_compra (Cal_distancia Lat_motorista Long_motorista Lat_compra Long_compra))
	(setq Distancia_entrega (Cal_distancia Lat_compra Long_compra Lat_entrega Long_entrega))

	(format t "Estabelecimento da compra: ~A" Loc_compra_aux)
	(terpri)
	(format t "Distancia ate o estabelecimento ~A" Distancia_compra)
	(terpri)
	(setq Tempo_compra (/ Distancia_compra 30))
	(format t "Chegara no estabelecimento aproximidamente em (min):  ~A" (* Tempo_compra 56.528))
	(terpri)
	(format t "Distancia ate voce (Km): ~A" Distancia_entrega)
	(terpri)
	(setq Tempo_entrega (/ Distancia_entrega 30))
	(format t "Chegara ate voce em (min):  ~A" (* Tempo_entrega 56.528))
)
